spring:
  application:
   name: authentication_service

  data:
    kafka:
      port: 9092
      host: localhost

    channel:
      notification:
        name: notification_channel

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
     hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgresql

  liquibase:
    change-log: classpath:/db/migration/changelog/db.changelog-master.yaml

server:
  port: 9000
  servlet:
    context-path: /v1/api

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    access_token_expiration: 36000
    refresh_token_expiration: 86400
    access_secret: kymtrhewfgjklhiuydfvxbnmbliuytrefdvc
    refresh_secret: kymtrhewfgjklhiuydfvxbnmbliuytrefdvc



logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
