spring:
  data:
    kafka:
      port: 9092
      host: localhost
      group-id: notification_service
    channel:
      notification:
        name: notification_channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxxxxx@gmail.com
    password: xxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000

  messages:
    basename: messages

server:
  port: 8091

logging:
  level:
    root: info

authentication-service:
  host: localhost
  port: 8092
